Algoritmo "Questão 4"
// 4)Fazer um pograma que pergunte
//seu sucessor e seu antecessor
Var
// Seção de Declarações das variáveis 
ante,suce,num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Coloque um número:")
leia(num)

escreval("aqui está o sucessor do seu número", num, " é ", (num - 1))
escreval("aqui está o antecessor do seu número", num, " é ", (num + 1))

Fimalgoritmo