Algoritmo "Questão 7"
// Fazer um algaritimo que apresente 3 números
// E apresente a média aritmética entre os 3 números
Var
// Seção de Declarações das variáveis 
n1, n2, n3, m: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Coloque número 1: ")
leia(n1)

escreval("Coloque número 2: ")
leia(n2)

escreval("Coloque número 3: ")
leia(n3)


m <- (n1 +n2 + n3) / 3
escreval("Aqui está a sua média", m )


Fimalgoritmo