Algoritmo "Questão 1"
// 1) Desenvolver um programa que pergunte ao
//usuário o seu nome completo e seu sexo.
//Em seguida, o programa deve apresentar os
//dados anteriormente informados.
Var
// Seção de Declarações das variáveis 
nome, sexo: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("seu nome:")
leia(nome)

escreva("seu sexo:")
leia(sexo)

escreval("Olá! ", nome, " Seja bem-vindo(a)!")
escreval("O sexo informado é " , sexo)

Fimalgoritmo